name: flutter_seringueiro
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_dotenv:
  flutter_localizations:
    sdk: flutter
  table_calendar:
  cupertino_icons:
  intl: 0.18.1
  flutter_masked_text2:
  validators:
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  flutter_bloc:
  google_maps_flutter:
  equatable:
  geolocator:
  hive:
  hive_flutter:
  sensors_plus:
  connectivity_plus:
  build_runner:
  hive_generator: ^2.0.1
  permission_handler:
  url_launcher: ^6.2.4
  flutter_launcher_icons:
  image_picker:
  firebase_storage: ^11.6.9
  fl_chart:
  flutter_svg:
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  package_info_plus: ^5.0.1
  geocoding: ^3.0.0
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/weather_icons/
    - assets/logo_vetorial.svg
    - assets/pluviometro.png
    - assets/seringueira.svg
    - .env

flutter_launcher_icons: 
  android: true
  ios: true
  image_path: "assets/icon.png"
