name: flutter_seringueiro
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.1.0  # Versão atualizada da biblioteca flutter_dotenv
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  weather_icons: ^3.0.0
  flutter_typeahead: ^5.0.1
  flutter_masked_text2: ^0.9.1
  validators: ^3.0.0
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  flutter_bloc: ^8.1.3
  google_maps_flutter: ^2.5.0
  equatable: ^2.0.5
  geolocator: ^10.1.0
  flutter_vibrate: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sensors: ^2.0.3
  vibration: ^1.8.4
  connectivity_plus: ^5.0.2
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env  # Adicionando o arquivo .env aos assets

# (O restante do arquivo permanece o mesmo)
