name: flutter_seringueiro
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.1.0  # Versão atualizada da biblioteca flutter_dotenv
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env  # Adicionando o arquivo .env aos assets

# (O restante do arquivo permanece o mesmo)
