// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4KBGzY9jE67g7IlhhUsxOVMd6NCwfkIU',
    appId: '1:699625603364:web:cc24f9994cb7db439473b1',
    messagingSenderId: '699625603364',
    projectId: 'seringueiroapp',
    authDomain: 'seringueiroapp.firebaseapp.com',
    databaseURL: 'https://seringueiroapp-default-rtdb.firebaseio.com',
    storageBucket: 'seringueiroapp.appspot.com',
    measurementId: 'G-FSZS58C0BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbwakF8efURz0oDhA37jwPNVXzp-UmyAo',
    appId: '1:699625603364:android:4fe2f10c94b5c4c49473b1',
    messagingSenderId: '699625603364',
    projectId: 'seringueiroapp',
    databaseURL: 'https://seringueiroapp-default-rtdb.firebaseio.com',
    storageBucket: 'seringueiroapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGkBD3eGZpeqodOko6ldo_mpPbznBwRLQ',
    appId: '1:699625603364:ios:e35b846dfc1d22159473b1',
    messagingSenderId: '699625603364',
    projectId: 'seringueiroapp',
    databaseURL: 'https://seringueiroapp-default-rtdb.firebaseio.com',
    storageBucket: 'seringueiroapp.appspot.com',
    iosBundleId: 'com.example.flutterSeringueiro',
  );
}
